# Generated by Django 2.2 on 2020-08-06 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.TextField(default='No desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='network',
            field=models.CharField(default='No network', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='No title', max_length=255),
            preserve_default=False,
        ),
    ]
